import { useMemo, useState } from 'react';
import { Accordion } from '@swift/components/Accordion';
import { Badge } from '@swift/components/Badge';
import { SegmentedControl } from '@swift/components/SegmentedControl';
import { Text } from '@swift/components/Text';
import { ExpandMore } from '@swift/icons/ExpandMore';
import faqGraphic from '../faqs.avif';

type CategoryKey =
    | 'basics'
    | 'savings'
    | 'subsidy'
    | 'install'
    | 'care';

const categories: { key: CategoryKey; label: string }[] = [
    { key: 'basics', label: 'Basics' },
    { key: 'savings', label: 'Savings' },
    { key: 'subsidy', label: 'Subsidy' },
    { key: 'install', label: 'Install' },
    { key: 'care', label: 'System & Care' },
];

type Faq = {
    category: CategoryKey;
    question: string;
    answer: string;
};

// Verbatim FAQs from solarsquare.in
const faqs: Faq[] = [
    {
        category: 'basics',
        question: 'What is SolarSquare?',
        answer:
            'SolarSquare designs and installs solar panel systems for homes, housing societies and businesses. With a relentless commitment to innovation and excellence, we’re driving the Har Ghar Solar mission forward, one rooftop at a time. Established in 2015 by a passionate trio of solar enthusiasts — Shreya Mishra, Neeraj Jain, and Nikhil Nahar — SolarSquare is India’s most trusted residential solar company. We believe in the power of solar to not only reduce carbon footprints but also to revolutionise the way we power our homes and businesses.',
    },
    {
        category: 'basics',
        question: 'What is a solar rooftop system?',
        answer:
            'A solar rooftop system is a combination of many components that convert sunlight into usable electricity. The components of a rooftop solar include the following – Solar panels with PV cells, Solar inverter, Solar panel mounting structures, AC and DC cables, AC combiner box, DC combiner box, Earthing cables, MC4 connectors',
    },
    {
        category: 'basics',
        question: 'How does a solar rooftop system work?',
        answer:
            'A solar rooftop system works on the concept of conversion of sunlight into electricity. The phenomenon is known as the photovoltaic effect. When sunlight falls on the PV cells in a solar panel, the sunlight is converted into electricity. The generated power is DC current. An AC combiner box is used to convert that DC power into usable AC power. The generated AC electricity is fed into a bidirectional meter that supplies power to the house. It also exports excess power to the DISCOM (grid) and imports power from the grid if electricity generated by the rooftop solar system is not enough to cover the daily requirement.',
    },
    {
        category: 'basics',
        question: 'Why should I switch to solar?',
        answer:
            'If you are dealing with high electricity bills, tapping into solar power is your best way to bring them down. Apart from the rising cost of electricity, solar power also helps you reduce dependency on the grid and reduce your carbon footprint.',
    },
    {
        category: 'basics',
        question: 'Is solar power safe?',
        answer:
            'Yes. The electricity produced by a solar power system is no different than the electricity you get from your electricity distribution company. The only difference is the source. Moreover, it is among the safest source of electricity consumption because it is neither hazardous nor does it release any toxic or harmful gases during production.',
    },
    {
        category: 'basics',
        question: 'What makes SolarSquare different from other solar providers?',
        answer:
            'We handle everything for you end-to-end: design, installation, subsidy paperwork, financing, and even offer you 5-year free maintenance. We are a no middlemen service. We are also India’s only solar company to offer Guaranteed Savings with a money-back promise.',
    },
    {
        category: 'basics',
        question: 'What are the different types of Solar systems?',
        answer:
            'There are 3 types of Solar systems depending on whether the plant is linked to the power grid or battery systems for storage. On-grid solar systems use common solar inverters and are connected to the public electricity grid. Any excess solar power that you generate is exported to the electricity grid and one usually get paid a feed-in-tariff or credits for the energy you export. The policy for getting credits for energy exported to the credit is termed as “Net-Metering Policy” and is available currently in most states of India. Off-grid solar systems are not connected to the electricity grid and therefore requires battery storage. An off-grid solar system must be designed appropriately so that it will generate enough power throughout the year and have enough battery capacity to meet the home’s requirements, even in the depths of winter when there is less sunlight. Hybrid solar systems combines solar and battery storage in one and are now available in many different forms and configurations. This means being able to store solar energy that is generated during the day and using it at night. When the stored energy is depleted, the grid is there as backup, allowing consumers to have the best of both worlds.',
    },
    {
        category: 'savings',
        question:
            'How high does my electricity bill need to be for solar to make sense for me?',
        answer:
            'We offer solar solutions for homes of all sizes. However, we’ve found that the overall investment into a solar system works out best economically for homes with electricity bills starting at ₹1,500.',
    },
    {
        category: 'savings',
        question: 'How much can I actually save with solar?',
        answer:
            'Most homeowners cut their electricity bills by 80–90% from Day 1. And with rising tariffs, your savings only keep growing every year.',
    },
    {
        category: 'savings',
        question: 'Do solar panels alone guarantee long-term savings?',
        answer:
            'Panels are only one part of the system. Besides the quality of your solar panels, your long-term savings depend on system design, strong mounting structure, and regular maintenance. If any of these are weak, your power generation (and savings) from rooftop solar will drop over time. With SolarSquare’s professionally engineered system and regular maintenance, you’ll enjoy consistent, high savings for 25+ years.',
    },
    {
        category: 'savings',
        question: 'How much does a solar Plant cost?',
        answer:
            'The cost of a solar plant depends on its size, configuration and degree of supporting structures required. We provide you multiple options to choose from, designed specifically to meet your requirements.',
    },
    {
        category: 'savings',
        question: 'What is the break-even period for Solar rooftop projects?',
        answer:
            'Rooftop solar projects are among the most lucrative investments for industrial, commercial and residential projects. The breakeven is achieved in 2-4 years itself, while you enjoy savings for the project life of 25 years.',
    },
    {
        category: 'subsidy',
        question: 'Do I need to pay a huge amount upfront?',
        answer:
            'No. With flexible EMIs starting low, you can go solar without any initial investment. The government subsidy pays for your down payment and bill savings often cover the EMI.',
    },
    {
        category: 'subsidy',
        question: 'How complicated is the solar subsidy process?',
        answer:
            'We understand you may be apprehensive about the paperwork, but we manage the whole thing for you. You won’t have to lift a finger.',
    },
    {
        category: 'subsidy',
        question:
            'Are there any subsidies provided by the government for solar projects?',
        answer:
            'There are no subsidies available for commercial entities. For residential rooftop solar projects, subsidies are released by the government within 30 days. Whenever a subsidy is applicable, SolarSquare assists you throughout the entire process—from application to disbursement—ensuring you receive the subsidy amount. The various slabs of subsidy are – Individual house 1kW ₹30,000/-, Individual house 2kW ₹60,000/-, Individual house Above 3kW ₹78,000/-, Group Housing Societies/Residential Welfare Associations Rs 18,000/kw. At present, the Uttar Pradesh state government provides an additional solar subsidy of ₹15,000 per kw (max ₹30,000) when you install a rooftop solar system, bringing the total maximum subsidy amount to ₹1,08,000.',
    },
    {
        category: 'subsidy',
        question: 'Are financing options available for Solar Rooftop projects?',
        answer:
            'SolarSquare Energy provides lucrative EMI options while also facilitating collateral free loan facilities provided by various banking institutions for solar projects.',
    },
    {
        category: 'install',
        question: 'How do I decide what size of plant I need?',
        answer:
            'The size of your Solar plant depends on the following factors – Your electricity consumption pattern, Available shadow free area, Solar irradiation in your area. Once you enlist your interest in a solar project, SolarSquare conducts a scientific mapping of the appropriate project size for you.',
    },
    {
        category: 'install',
        question: 'I’m not sure if I have enough space for a solar system.',
        answer:
            'Not to worry. Once you share your details with us, you get a free home visit from our solar consultant who will evaluate your space and power needs and give you a free personalised 3D rooftop solar design for your home. You only need to proceed if you are happy with the offered solution.',
    },
    {
        category: 'install',
        question: 'How long does it take to set up the solar system?',
        answer:
            'Once we have visited your home and you’ve approved the 3D rooftop solar design, the installation is done in 1 day – based on your availability, the space and weather conditions.',
    },
    {
        category: 'install',
        question: 'What do I need to install a rooftop solar system?',
        answer:
            'All you need to qualify for a solar system is – empty space on your roof and access to your rooftop. Just fill the project enquiry form on our website and our team will contact you to discuss your requirement. Once the project is finalised, we will take care of your entire plant design, installation and maintenance.',
    },
    {
        category: 'install',
        question: 'Can Solar projects damage my roof?',
        answer:
            'SolarSquare Energy has a UL certification (one of the highest quality and safety standards in the world) and ensures that no damage to the existing structures takes place during the installation or running of the solar plant. We use a multitude of techniques like non-penetrating structures and waterproofing solutions to ensure your roof’s integrity.',
    },
    {
        category: 'install',
        question:
            'My roof is not made of concrete; can I still install a Solar Project?',
        answer:
            'Solar power plants can be installed on almost any type of roofs irrespective of their shape or material type. In cases where the construction material is brittle (Asbestos) or the roof integrity is compromised, SolarSquare Energy provides roof replacement solutions as part of the solar rooftop project.',
    },
    {
        category: 'care',
        question: 'What is the lifespan of a rooftop solar system?',
        answer:
            'A high-quality rooftop solar system lasts 25 years or more. The panels keep generating clean power for decades, and with SolarSquare’s 5-year free maintenance and performance checks, your system stays in top shape throughout its life.',
    },
    {
        category: 'care',
        question: 'How will I know how much power my system is generating?',
        answer:
            'We have an app that’s connected to your system, where you can monitor your power generation in real time and get 100% visibility on your savings.',
    },
    {
        category: 'care',
        question:
            'Do solar panels generate electricity even during monsoon and winter?',
        answer:
            'Yes, Solar panels do produce electricity in cloudy or rainy weather albeit with reduced efficiency. This fall in production is considered in the unit generation estimates provided for every project.',
    },
    {
        category: 'care',
        question:
            'Does a rooftop solar PV generate power during a power failure?',
        answer:
            'No, rooftop solar PV does not function or generate electricity during a blackout due to safety reasons. Since blackouts occur when the electricity grid is damaged. If a solar inverter was still feeding electricity into a damaged grid it would risk the safety of the people repairing the fault in the network. SolarSquare Energy provides the option of using a Li-ion storage battery with Solar power plants for areas which suffer from frequent power failures. This battery unit can store the excess electricity produced during the day and acts as a backup for any electricity requirement during night or in the event of a power failure.',
    },
    {
        category: 'care',
        question: 'What kind of appliances can I use on Solar Power?',
        answer:
            'Solar Power plants are used to power all types of heavy machinery in industrial plants as well as household electrical and electronic appliances. Since the electricity produced from the plant is fed in sync with your grid/diesel generator, there are no voltage fluctuations irrespective of the number of appliances you use.',
    },
    {
        category: 'care',
        question: 'Do I need to clean my Solar plant?',
        answer:
            'It is a good practice to clean the solar panels 1-2 times a month. It is safer to clean the panels early in the morning or at night when no incident sun rays are present and the power plant is not producing any electricity. You can simply use a clean wet cloth, soft nylon brush or sponge to wipe the surface but ensure the panels are clear of any moisture. Don’t use metal brushes or detergents as these may streak the glass of the panel.',
    },
];

function FaqSection() {
    const [active, setActive] = useState<CategoryKey>('basics');

    const filtered = useMemo(
        () => faqs.filter((faq) => faq.category === active),
        [active],
    );

    return (
        <section
            id="faq"
            className="section-seam relative bg-surface-muted py-20 text-content"
        >
            {/* Backdrop: diagonal hatching fading toward the center */}
            <div
                aria-hidden="true"
                className="pointer-events-none absolute inset-0 bg-diagonal-lines"
            />
            <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                <div className="grid gap-10 lg:grid-cols-[minmax(0,24rem)_minmax(0,1fr)] lg:gap-16">
                    {/* Left — intro + graphic (sticky on desktop) */}
                    <div className="flex flex-col gap-6 lg:sticky lg:top-24 lg:self-start">
                        <div className="flex flex-col gap-3">
                            <Badge
                                pill
                                variant="info"
                                appearance="soft"
                                className="w-fit uppercase tracking-wider"
                            >
                                FAQ
                            </Badge>
                            <Text variant="heading-lg" fontWeight="bold">
                                Questions? We’ve Got Answers
                            </Text>
                            <Text variant="para-md" className='text-content-muted'>
                                Everything you need to know about going solar
                                with us. Pick a topic to jump in.
                            </Text>
                        </div>

                        <img
                            src={faqGraphic}
                            alt=""
                            className="w-full max-w-sm rounded-2xl"
                        />
                    </div>

                    {/* Right — filter on top, then answers */}
                    <div className="min-w-0">
                        <div className="overflow-x-auto pb-1">
                            <SegmentedControl
                                value={active}
                                onValueChange={(value) =>
                                    setActive(value as CategoryKey)
                                }
                                size="md"
                                fullWidth
                                aria-label="FAQ categories"
                            >
                                <SegmentedControl.Indicator />
                                {categories.map((category) => (
                                    <SegmentedControl.Item
                                        key={category.key}
                                        value={category.key}
                                    >
                                        {category.label}
                                    </SegmentedControl.Item>
                                ))}
                            </SegmentedControl>
                        </div>

                        {/* Answers — remounts on category change to replay the stagger */}
                        <Accordion
                            key={active}
                            type="single"
                            collapsible
                            defaultValue="q0"
                            className="mt-6 shadow-level1"
                        >
                            {filtered.map((faq, index) => (
                                <Accordion.Item
                                    key={faq.question}
                                    value={`q${index}`}
                                    className="animate__animated animate__fadeInUpShort"
                                    style={{
                                        animationDelay: `${index * 60}ms`,
                                    }}
                                >
                                    <Accordion.Header>
                                        <Accordion.Trigger>
                                            {faq.question}
                                            <ExpandMore
                                                size={20}
                                                className="shrink-0 text-content-muted transition-transform duration-300 group-data-[state=open]/accordion-item:rotate-180"
                                            />
                                        </Accordion.Trigger>
                                    </Accordion.Header>
                                    <Accordion.Content>
                                        <Text
                                            variant="para-md"
                                            className='text-content-muted'
                                        >
                                            {faq.answer}
                                        </Text>
                                    </Accordion.Content>
                                </Accordion.Item>
                            ))}
                        </Accordion>
                    </div>
                </div>
            </div>
        </section>
    );
}

export default FaqSection;
