/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolarSquareRouteImport } from './routes/solar-square'
import { Route as IconsRouteImport } from './routes/icons'
import { Route as FoundationsRouteImport } from './routes/foundations'
import { Route as CssRouteImport } from './routes/css'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as IndexRouteImport } from './routes/index'

const SolarSquareRoute = SolarSquareRouteImport.update({
  id: '/solar-square',
  path: '/solar-square',
  getParentRoute: () => rootRouteImport,
} as any)
const IconsRoute = IconsRouteImport.update({
  id: '/icons',
  path: '/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsRoute = FoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const CssRoute = CssRouteImport.update({
  id: '/css',
  path: '/css',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/css': typeof CssRoute
  '/foundations': typeof FoundationsRoute
  '/icons': typeof IconsRoute
  '/solar-square': typeof SolarSquareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/css': typeof CssRoute
  '/foundations': typeof FoundationsRoute
  '/icons': typeof IconsRoute
  '/solar-square': typeof SolarSquareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/css': typeof CssRoute
  '/foundations': typeof FoundationsRoute
  '/icons': typeof IconsRoute
  '/solar-square': typeof SolarSquareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/css'
    | '/foundations'
    | '/icons'
    | '/solar-square'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components' | '/css' | '/foundations' | '/icons' | '/solar-square'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/css'
    | '/foundations'
    | '/icons'
    | '/solar-square'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  CssRoute: typeof CssRoute
  FoundationsRoute: typeof FoundationsRoute
  IconsRoute: typeof IconsRoute
  SolarSquareRoute: typeof SolarSquareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solar-square': {
      id: '/solar-square'
      path: '/solar-square'
      fullPath: '/solar-square'
      preLoaderRoute: typeof SolarSquareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icons': {
      id: '/icons'
      path: '/icons'
      fullPath: '/icons'
      preLoaderRoute: typeof IconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations': {
      id: '/foundations'
      path: '/foundations'
      fullPath: '/foundations'
      preLoaderRoute: typeof FoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/css': {
      id: '/css'
      path: '/css'
      fullPath: '/css'
      preLoaderRoute: typeof CssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  CssRoute: CssRoute,
  FoundationsRoute: FoundationsRoute,
  IconsRoute: IconsRoute,
  SolarSquareRoute: SolarSquareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
